version: "3.8"

services:
  api:
    build: .
    container_name: internship_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
